/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.openmemind.ai.memory.core.data;

import com.openmemind.ai.memory.core.data.enums.InsightTier;
import com.openmemind.ai.memory.core.data.enums.MemoryScope;
import java.time.Instant;
import java.util.List;
import java.util.stream.Collectors;

public record MemoryInsight(
        Long id,
        String memoryId,

        /* Insight type (related to MemoryInsightType#getName) */
        String type,

        /* Ownership scope */
        MemoryScope scope,

        /* Short name/title */
        String name,

        /* Associated category list */
        List<String> categories,

        /* Structured point list (replaces old summary + reasonings) */
        List<InsightPoint> points,

        /* Subgroup name (generated by LLM grouping, nullable) */
        String group,

        /* Last reasoning time */
        Instant lastReasonedAt,

        /* Embedding vector of summary (precomputed when written) */
        List<Float> summaryEmbedding,

        /* Creation time */
        Instant createdAt,

        /* Last update time */
        Instant updatedAt,

        // === Tree structure fields ===

        /* Insight tree level (LEAF/BRANCH/ROOT), null is considered LEAF */
        InsightTier tier,

        /* Parent Insight ID (Root is null) */
        Long parentInsightId,

        /* Child Insight ID list (Leaf is empty) */
        List<Long> childInsightIds,

        /* Version number, +1 for each summary update */
        int version) {

    /**
     * Concatenate all point.content(), used for embedding calculation
     */
    public String pointsContent() {
        if (points == null || points.isEmpty()) {
            return "";
        }
        return points.stream().map(InsightPoint::content).collect(Collectors.joining("\n"));
    }

    // ===== Wither methods =====

    public MemoryInsight withPoints(List<InsightPoint> points) {
        return new MemoryInsight(
                id,
                memoryId,
                type,
                scope,
                name,
                categories,
                points,
                group,
                lastReasonedAt,
                summaryEmbedding,
                createdAt,
                updatedAt,
                tier,
                parentInsightId,
                childInsightIds,
                version);
    }

    public MemoryInsight withSummaryEmbedding(List<Float> summaryEmbedding) {
        return new MemoryInsight(
                id,
                memoryId,
                type,
                scope,
                name,
                categories,
                points,
                group,
                lastReasonedAt,
                summaryEmbedding,
                createdAt,
                updatedAt,
                tier,
                parentInsightId,
                childInsightIds,
                version);
    }

    public MemoryInsight withParentInsightId(Long parentInsightId) {
        return new MemoryInsight(
                id,
                memoryId,
                type,
                scope,
                name,
                categories,
                points,
                group,
                lastReasonedAt,
                summaryEmbedding,
                createdAt,
                updatedAt,
                tier,
                parentInsightId,
                childInsightIds,
                version);
    }

    public MemoryInsight withChildInsightIds(List<Long> childInsightIds) {
        return new MemoryInsight(
                id,
                memoryId,
                type,
                scope,
                name,
                categories,
                points,
                group,
                lastReasonedAt,
                summaryEmbedding,
                createdAt,
                updatedAt,
                tier,
                parentInsightId,
                childInsightIds,
                version);
    }

    public MemoryInsight withVersion(int version) {
        return new MemoryInsight(
                id,
                memoryId,
                type,
                scope,
                name,
                categories,
                points,
                group,
                lastReasonedAt,
                summaryEmbedding,
                createdAt,
                updatedAt,
                tier,
                parentInsightId,
                childInsightIds,
                version);
    }

    public MemoryInsight withLastReasonedAt(Instant lastReasonedAt) {
        return new MemoryInsight(
                id,
                memoryId,
                type,
                scope,
                name,
                categories,
                points,
                group,
                lastReasonedAt,
                summaryEmbedding,
                createdAt,
                updatedAt,
                tier,
                parentInsightId,
                childInsightIds,
                version);
    }

    public MemoryInsight withUpdatedAt(Instant updatedAt) {
        return new MemoryInsight(
                id,
                memoryId,
                type,
                scope,
                name,
                categories,
                points,
                group,
                lastReasonedAt,
                summaryEmbedding,
                createdAt,
                updatedAt,
                tier,
                parentInsightId,
                childInsightIds,
                version);
    }

    public MemoryInsight withTier(InsightTier tier) {
        return new MemoryInsight(
                id,
                memoryId,
                type,
                scope,
                name,
                categories,
                points,
                group,
                lastReasonedAt,
                summaryEmbedding,
                createdAt,
                updatedAt,
                tier,
                parentInsightId,
                childInsightIds,
                version);
    }

    public MemoryInsight withCreatedAt(Instant createdAt) {
        return new MemoryInsight(
                id,
                memoryId,
                type,
                scope,
                name,
                categories,
                points,
                group,
                lastReasonedAt,
                summaryEmbedding,
                createdAt,
                updatedAt,
                tier,
                parentInsightId,
                childInsightIds,
                version);
    }

    /**
     * Collect all sourceItemIds from points (deduplicated)
     */
    public List<String> allSourceItemIds() {
        if (points == null || points.isEmpty()) {
            return List.of();
        }
        return points.stream()
                .filter(p -> p.sourceItemIds() != null)
                .flatMap(p -> p.sourceItemIds().stream())
                .distinct()
                .toList();
    }
}
