/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.openmemind.ai.memory.core.retrieval.tier;

import com.openmemind.ai.memory.core.data.MemoryRawData;
import com.openmemind.ai.memory.core.retrieval.RetrievalConfig;
import com.openmemind.ai.memory.core.retrieval.deep.ExpandedQuery;
import com.openmemind.ai.memory.core.retrieval.query.QueryContext;
import com.openmemind.ai.memory.core.retrieval.scoring.ResultMerger;
import com.openmemind.ai.memory.core.retrieval.scoring.ScoredResult;
import com.openmemind.ai.memory.core.retrieval.scoring.ScoringConfig;
import com.openmemind.ai.memory.core.retrieval.truncation.AdaptiveTruncator;
import com.openmemind.ai.memory.core.store.MemoryStore;
import com.openmemind.ai.memory.core.textsearch.MemoryTextSearch;
import com.openmemind.ai.memory.core.textsearch.TextSearchResult;
import com.openmemind.ai.memory.core.vector.MemoryVector;
import com.openmemind.ai.memory.core.vector.VectorSearchResult;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Tier 3: RawData Retrieval
 *
 * <p>Vector search MemoryRawData.caption, BM25 search segment.content, RRF fusion to extract KeyInfo
 *
 */
public class RawDataTierRetriever implements TierSearchable {

    private static final Logger log = LoggerFactory.getLogger(RawDataTierRetriever.class);

    private final MemoryStore memoryStore;
    private final MemoryVector memoryVector;
    private final MemoryTextSearch textSearch;

    /** Backward compatible constructor (no full-text search support) */
    public RawDataTierRetriever(MemoryStore memoryStore, MemoryVector memoryVector) {
        this(memoryStore, memoryVector, null);
    }

    /**
     * Complete constructor (supports full-text search fusion and KeyInfo extraction)
     *
     * @param memoryStore Memory storage
     * @param memoryVector Vector search
     * @param textSearch Full-text search (nullable, skip keyword fusion when null)
     */
    public RawDataTierRetriever(
            MemoryStore memoryStore, MemoryVector memoryVector, MemoryTextSearch textSearch) {
        this.memoryStore = Objects.requireNonNull(memoryStore, "memoryStore must not be null");
        this.memoryVector = Objects.requireNonNull(memoryVector, "memoryVector must not be null");
        this.textSearch = textSearch;
    }

    /**
     * Execute Tier 3 retrieval (no expanded query, delegated to overloaded with expanded query)
     *
     * @param context    Query context
     * @param config     Retrieval configuration
     * @param scopeHints RawDataId scope constraints passed from Tier 2 (empty list means no constraints)
     * @return Single-layer result (scopeHints is empty, no need to pass the last layer)
     */
    public Mono<TierResult> retrieve(
            QueryContext context, RetrievalConfig config, List<String> scopeHints) {
        return retrieve(context, config, scopeHints, List.of());
    }

    /**
     * Execute Tier 3 retrieval (supports reusing Tier 2 expanded queries for multi-channel RRF fusion)
     *
     * @param context         Query context
     * @param config          Retrieval configuration
     * @param scopeHints      RawDataId scope constraints passed from Tier 2 (empty list means no constraints)
     * @param expandedQueries Expanded queries generated by Tier 2 (empty list means no expansion)
     * @return Single-layer result
     */
    public Mono<TierResult> retrieve(
            QueryContext context,
            RetrievalConfig config,
            List<String> scopeHints,
            List<ExpandedQuery> expandedQueries) {
        if (!config.tier3().enabled()) {
            return Mono.just(TierResult.empty());
        }

        int topK = config.tier3().topK();
        double minScore = config.tier3().minScore();
        Set<String> rawDataIdScope =
                scopeHints != null && !scopeHints.isEmpty() ? Set.copyOf(scopeHints) : Set.of();

        return executeMultiChannelRetrieval(
                context, config, topK, minScore, rawDataIdScope, expandedQueries);
    }

    /**
     * Multi-channel retrieval: original vector + BM25 + expanded query channel → RRF merge → KeyInfo → truncation
     */
    private Mono<TierResult> executeMultiChannelRetrieval(
            QueryContext context,
            RetrievalConfig config,
            int topK,
            double minScore,
            Set<String> rawDataIdScope,
            List<ExpandedQuery> expandedQueries) {

        Mono<List<VectorSearchResult>> originalVectorResultsMono =
                searchOriginalVectorResults(context, config, topK, minScore);
        Mono<List<ScoredResult>> originalBm25Mono = executeBm25Channel(context, topK);

        List<ExpandedQuery> safeExpandedQueries =
                expandedQueries == null ? List.of() : expandedQueries;
        Mono<List<List<VectorSearchResult>>> expandedVectorHitsMono =
                Flux.fromIterable(safeExpandedQueries)
                        .filter(
                                eq ->
                                        eq.queryType() == ExpandedQuery.QueryType.VEC
                                                || eq.queryType() == ExpandedQuery.QueryType.HYDE)
                        .flatMap(
                                eq ->
                                        searchExpandedVectorResults(
                                                        eq, context, config, topK, minScore)
                                                .onErrorResume(
                                                        e -> {
                                                            log.warn(
                                                                    "Tier3 expanded vector channel"
                                                                            + " search failed:"
                                                                            + " type={}, text={}",
                                                                    eq.queryType(),
                                                                    eq.text(),
                                                                    e);
                                                            return Mono.just(List.of());
                                                        }))
                        .collectList();
        Mono<List<List<ScoredResult>>> expandedLexChannelsMono =
                Flux.fromIterable(safeExpandedQueries)
                        .filter(eq -> eq.queryType() == ExpandedQuery.QueryType.LEX)
                        .flatMap(
                                eq ->
                                        executeExpandedLexChannel(eq, context, topK)
                                                .onErrorResume(
                                                        e -> {
                                                            log.warn(
                                                                    "Tier3 expanded lex channel"
                                                                            + " search failed:"
                                                                            + " type={}, text={}",
                                                                    eq.queryType(),
                                                                    eq.text(),
                                                                    e);
                                                            return Mono.just(List.of());
                                                        }))
                        .collectList();

        return Mono.zip(
                        originalVectorResultsMono,
                        originalBm25Mono,
                        expandedVectorHitsMono,
                        expandedLexChannelsMono)
                .map(
                        tuple -> {
                            List<VectorSearchResult> originalVectorHits = tuple.getT1();
                            List<ScoredResult> bm25Results = tuple.getT2();
                            List<List<VectorSearchResult>> expandedVectorHits = tuple.getT3();
                            List<List<ScoredResult>> expandedLexResults = tuple.getT4();

                            List<String> vectorIds = new ArrayList<>();
                            vectorIds.addAll(collectVectorIds(originalVectorHits));
                            expandedVectorHits.forEach(
                                    hits -> vectorIds.addAll(collectVectorIds(hits)));
                            Map<String, MemoryRawData> vectorIdToRawData =
                                    buildVectorIdToRawDataMap(context, vectorIds, rawDataIdScope);
                            List<ScoredResult> vectorResults =
                                    toScoredResults(
                                            originalVectorHits, vectorIdToRawData, config, topK);
                            List<List<ScoredResult>> expandedVectorResults =
                                    expandedVectorHits.stream()
                                            .map(
                                                    hits ->
                                                            toScoredResults(
                                                                    hits,
                                                                    vectorIdToRawData,
                                                                    config,
                                                                    topK))
                                            .toList();

                            // Build ranking list and weights
                            List<List<ScoredResult>> rankedLists = new ArrayList<>();
                            List<Double> weightsList = new ArrayList<>();

                            if (!vectorResults.isEmpty()) {
                                rankedLists.add(vectorResults);
                                weightsList.add(config.scoring().queryWeight().originalWeight());
                            }
                            if (!bm25Results.isEmpty()) {
                                rankedLists.add(bm25Results);
                                weightsList.add(config.scoring().queryWeight().originalWeight());
                            }
                            for (List<ScoredResult> channelResults : expandedVectorResults) {
                                if (!channelResults.isEmpty()) {
                                    rankedLists.add(channelResults);
                                    weightsList.add(
                                            config.scoring().queryWeight().expandedWeight());
                                }
                            }
                            for (List<ScoredResult> channelResults : expandedLexResults) {
                                if (!channelResults.isEmpty()) {
                                    rankedLists.add(channelResults);
                                    weightsList.add(
                                            config.scoring().queryWeight().expandedWeight());
                                }
                            }

                            // RRF merge
                            List<ScoredResult> merged;
                            if (rankedLists.isEmpty()) {
                                merged = new ArrayList<>();
                            } else if (rankedLists.size() == 1) {
                                merged = new ArrayList<>(rankedLists.get(0));
                            } else {
                                double[] weights =
                                        weightsList.stream()
                                                .mapToDouble(Double::doubleValue)
                                                .toArray();
                                merged =
                                        new ArrayList<>(
                                                ResultMerger.merge(
                                                        config.scoring(), rankedLists, weights));
                            }

                            merged.sort(
                                    Comparator.comparingDouble(ScoredResult::finalScore)
                                            .reversed());

                            // KeyInfo extraction
                            List<ScoredResult> enriched =
                                    enrichWithKeyInfo(merged, context, rawDataIdScope, config);

                            // Adaptive truncation
                            var truncationResult =
                                    AdaptiveTruncator.truncate(
                                            enriched, config.tier3().truncation());

                            log.debug(
                                    "Tier 3 completed: {}/{} results",
                                    truncationResult.results().size(),
                                    truncationResult.originalSize());

                            return new TierResult(truncationResult.results(), List.of());
                        })
                .onErrorResume(
                        e -> {
                            log.warn(
                                    "Tier 3 (RawData) retrieval failed, returning empty result", e);
                            return Mono.just(TierResult.empty());
                        });
    }

    private Mono<List<VectorSearchResult>> searchOriginalVectorResults(
            QueryContext context, RetrievalConfig config, int topK, double minScore) {
        return memoryVector
                .search(
                        context.memoryId(),
                        context.searchQuery(),
                        topK * config.scoring().candidateMultiplier(),
                        minScore,
                        null)
                .collectList()
                .onErrorResume(
                        e -> {
                            log.warn("Tier3 vector channel search failed", e);
                            return Mono.just(List.of());
                        });
    }

    private Mono<List<VectorSearchResult>> searchExpandedVectorResults(
            ExpandedQuery eq,
            QueryContext baseContext,
            RetrievalConfig config,
            int topK,
            double minScore) {
        var ctx =
                new QueryContext(
                        baseContext.memoryId(),
                        baseContext.originalQuery(),
                        eq.text(),
                        baseContext.conversationHistory(),
                        baseContext.metadata(),
                        null,
                        null);
        return memoryVector
                .search(
                        ctx.memoryId(),
                        ctx.searchQuery(),
                        topK * config.scoring().candidateMultiplier(),
                        minScore,
                        null)
                .collectList();
    }

    /** BM25 keyword search channel */
    private Mono<List<ScoredResult>> executeBm25Channel(QueryContext context, int topK) {
        if (textSearch == null) {
            return Mono.just(List.of());
        }
        return textSearch
                .search(
                        context.memoryId(),
                        context.searchQuery(),
                        topK,
                        MemoryTextSearch.SearchTarget.RAW_DATA)
                .map(this::toBm25ScoredResults)
                .onErrorResume(
                        e -> {
                            log.warn("Tier3 BM25 channel search failed", e);
                            return Mono.just(List.of());
                        });
    }

    private Mono<List<ScoredResult>> executeExpandedLexChannel(
            ExpandedQuery eq, QueryContext baseContext, int topK) {
        if (textSearch == null) {
            return Mono.just(List.of());
        }
        return textSearch
                .search(
                        baseContext.memoryId(),
                        eq.text(),
                        topK,
                        MemoryTextSearch.SearchTarget.RAW_DATA)
                .map(this::toBm25ScoredResults);
    }

    /** Convert vector search results to ScoredResult */
    private List<ScoredResult> toScoredResults(
            List<VectorSearchResult> vectorResults,
            Map<String, MemoryRawData> vectorIdToRawData,
            RetrievalConfig config,
            int topK) {
        List<ScoredResult> results = new ArrayList<>();
        for (VectorSearchResult vr : vectorResults) {
            MemoryRawData rawData = vectorIdToRawData.get(vr.vectorId());
            if (rawData == null) {
                continue;
            }
            double finalScore = vr.score();
            results.add(
                    new ScoredResult(
                            ScoredResult.SourceType.RAW_DATA,
                            rawData.id(),
                            rawData.caption(),
                            vr.score(),
                            finalScore));
            if (results.size() >= topK) {
                break;
            }
        }
        return results;
    }

    /** Convert BM25 search results to ScoredResult */
    private List<ScoredResult> toBm25ScoredResults(List<TextSearchResult> hits) {
        return hits.stream()
                .map(
                        tr ->
                                new ScoredResult(
                                        ScoredResult.SourceType.RAW_DATA,
                                        tr.documentId(),
                                        tr.text(),
                                        0f,
                                        ResultMerger.sigmoidNormalize(tr.score())))
                .toList();
    }

    /**
     * enrichWithKeyInfo has been removed (content/keyInfo fields have been deleted from ScoredResult).
     * Retain method signature for compatibility with callers, directly return the original list.
     */
    private List<ScoredResult> enrichWithKeyInfo(
            List<ScoredResult> results,
            QueryContext context,
            Set<String> rawDataIdScope,
            RetrievalConfig config) {
        return results;
    }

    private Map<String, MemoryRawData> buildVectorIdToRawDataMap(
            QueryContext context, Collection<String> vectorIds, Set<String> rawDataIdScope) {
        List<String> effectiveVectorIds =
                vectorIds == null
                        ? List.of()
                        : vectorIds.stream().filter(Objects::nonNull).distinct().toList();
        if (effectiveVectorIds.isEmpty()) {
            return Map.of();
        }
        return memoryStore
                .rawDataOperations()
                .getRawDataByCaptionVectorIds(context.memoryId(), effectiveVectorIds)
                .stream()
                .filter(rd -> rd.captionVectorId() != null)
                .filter(rd -> rawDataIdScope.isEmpty() || rawDataIdScope.contains(rd.id()))
                .collect(
                        Collectors.toMap(
                                MemoryRawData::captionVectorId, Function.identity(), (a, b) -> a));
    }

    private static List<String> collectVectorIds(List<VectorSearchResult> results) {
        if (results == null || results.isEmpty()) {
            return List.of();
        }
        return results.stream()
                .map(VectorSearchResult::vectorId)
                .filter(Objects::nonNull)
                .distinct()
                .toList();
    }

    // ── TierSearchable Implementation ──

    /**
     * Pure vector search (TierSearchable interface method)
     *
     * <p>Encapsulate executeVectorChannel, does not go through scopeHints constraints (uses empty rawDataIdScope).
     */
    @Override
    public Mono<List<ScoredResult>> searchByVector(
            QueryContext context, RetrievalConfig.TierConfig tier, ScoringConfig scoring) {
        if (!tier.enabled()) {
            return Mono.just(List.of());
        }
        RetrievalConfig tempConfig = buildTempConfig(tier, scoring);
        return searchOriginalVectorResults(context, tempConfig, tier.topK(), tier.minScore())
                .map(
                        vectorResults -> {
                            Map<String, MemoryRawData> vectorIdToRawData =
                                    buildVectorIdToRawDataMap(
                                            context, collectVectorIds(vectorResults), Set.of());
                            return toScoredResults(
                                    vectorResults, vectorIdToRawData, tempConfig, tier.topK());
                        })
                .onErrorResume(
                        e -> {
                            log.warn("RawData searchByVector failed, returning empty result", e);
                            return Mono.just(List.of());
                        });
    }

    /**
     * Pure keyword (BM25) search (TierSearchable interface method)
     *
     * <p>Encapsulate executeBm25Channel.
     */
    @Override
    public Mono<List<ScoredResult>> searchByKeyword(
            QueryContext context, RetrievalConfig.TierConfig tier, ScoringConfig scoring) {
        if (!tier.enabled()) {
            return Mono.just(List.of());
        }
        return executeBm25Channel(context, tier.topK())
                .onErrorResume(
                        e -> {
                            log.warn("RawData searchByKeyword failed, returning empty result", e);
                            return Mono.just(List.of());
                        });
    }

    /**
     * Hybrid search (vector + BM25 RRF fusion) (TierSearchable interface method)
     *
     * <p>Parallel vector + BM25 → RRF merge, weights use scoring.fusion()'s vectorWeight/keywordWeight.
     */
    @Override
    public Mono<List<ScoredResult>> searchHybrid(
            QueryContext context, RetrievalConfig.TierConfig tier, ScoringConfig scoring) {
        if (!tier.enabled()) {
            return Mono.just(List.of());
        }
        RetrievalConfig tempConfig = buildTempConfig(tier, scoring);

        Mono<List<ScoredResult>> vectorMono =
                searchOriginalVectorResults(context, tempConfig, tier.topK(), tier.minScore())
                        .map(
                                vectorResults -> {
                                    Map<String, MemoryRawData> vectorIdToRawData =
                                            buildVectorIdToRawDataMap(
                                                    context,
                                                    collectVectorIds(vectorResults),
                                                    Set.of());
                                    return toScoredResults(
                                            vectorResults,
                                            vectorIdToRawData,
                                            tempConfig,
                                            tier.topK());
                                })
                        .onErrorResume(
                                e -> {
                                    log.warn("RawData searchHybrid vector channel failed", e);
                                    return Mono.just(List.of());
                                });
        Mono<List<ScoredResult>> bm25Mono =
                executeBm25Channel(context, tier.topK())
                        .onErrorResume(
                                e -> {
                                    log.warn("RawData searchHybrid BM25 channel failed", e);
                                    return Mono.just(List.of());
                                });

        return Mono.zip(vectorMono, bm25Mono)
                .map(
                        tuple -> {
                            List<ScoredResult> vectorResults = tuple.getT1();
                            List<ScoredResult> bm25Results = tuple.getT2();

                            if (vectorResults.isEmpty() && bm25Results.isEmpty()) {
                                return List.<ScoredResult>of();
                            }
                            if (vectorResults.isEmpty()) {
                                return bm25Results;
                            }
                            if (bm25Results.isEmpty()) {
                                return vectorResults;
                            }
                            return ResultMerger.merge(
                                    scoring,
                                    List.of(vectorResults, bm25Results),
                                    scoring.fusion().vectorWeight(),
                                    scoring.fusion().keywordWeight());
                        });
    }

    /** Build temporary RetrievalConfig for TierSearchable method delegation */
    private static RetrievalConfig buildTempConfig(
            RetrievalConfig.TierConfig tier, ScoringConfig scoring) {
        return new RetrievalConfig(
                RetrievalConfig.TierConfig.disabled(),
                RetrievalConfig.TierConfig.disabled(),
                tier,
                RetrievalConfig.RerankConfig.disabled(),
                scoring,
                java.time.Duration.ofSeconds(30),
                com.openmemind.ai.memory.core.retrieval.strategy.SimpleStrategyConfig.defaults());
    }
}
