--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- Squashed schema for postgresql.
-- This file supersedes the previous V1-V14 development migration chain.

-- === V1__init_store.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_raw_data (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id            VARCHAR(64)              NOT NULL,
    user_id           VARCHAR(64)              NOT NULL,
    agent_id          VARCHAR(64)              NOT NULL,
    memory_id         VARCHAR(200)             NOT NULL,
    type              VARCHAR(32)              NOT NULL,
    source_client     VARCHAR(64),
    content_id        VARCHAR(200),
    segment           JSONB,
    caption           TEXT,
    caption_vector_id VARCHAR(200),
    metadata          JSONB,
    start_time        TIMESTAMPTZ,
    end_time          TIMESTAMPTZ,
    created_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_raw_data_biz_id ON memory_raw_data(user_id, agent_id, biz_id);
CREATE INDEX IF NOT EXISTS idx_raw_data_content_id ON memory_raw_data(user_id, agent_id, content_id);
CREATE INDEX IF NOT EXISTS idx_raw_data_memory_id ON memory_raw_data(user_id, agent_id);
CREATE INDEX IF NOT EXISTS idx_raw_data_caption_vector_id
    ON memory_raw_data(user_id, agent_id, caption_vector_id);

CREATE TABLE IF NOT EXISTS memory_item (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id        BIGINT                   NOT NULL,
    user_id       VARCHAR(64)              NOT NULL,
    agent_id      VARCHAR(64)              NOT NULL,
    memory_id     VARCHAR(200)             NOT NULL,
    content       TEXT                     NOT NULL,
    scope         VARCHAR(16)              NOT NULL,
    category      VARCHAR(64),
    vector_id     VARCHAR(200),
    raw_data_id   VARCHAR(64),
    content_hash  VARCHAR(128),
    occurred_at   TIMESTAMPTZ,
    observed_at   TIMESTAMPTZ,
    type          VARCHAR(16)              NOT NULL DEFAULT 'FACT',
    raw_data_type VARCHAR(32)              NOT NULL DEFAULT 'CONVERSATION',
    source_client VARCHAR(64),
    metadata      JSONB,
    created_at    TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_biz_id ON memory_item(user_id, agent_id, biz_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_content_hash ON memory_item(user_id, agent_id, content_hash);
CREATE INDEX IF NOT EXISTS idx_item_memory_id ON memory_item(user_id, agent_id);
CREATE INDEX IF NOT EXISTS idx_item_raw_data_id ON memory_item(user_id, agent_id, raw_data_id);
CREATE INDEX IF NOT EXISTS idx_item_type ON memory_item(user_id, agent_id, type);
CREATE INDEX IF NOT EXISTS idx_item_category ON memory_item(memory_id, category);
CREATE INDEX IF NOT EXISTS idx_item_scope_category ON memory_item(memory_id, scope, category);

CREATE TABLE IF NOT EXISTS memory_insight_type (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id                BIGINT,
    name                  VARCHAR(128)             NOT NULL,
    description           TEXT,
    description_vector_id VARCHAR(200),
    categories            JSONB,
    target_tokens         INT                      NOT NULL DEFAULT 0,
    analysis_mode         VARCHAR(32)              DEFAULT 'BRANCH',
    scope                 VARCHAR(32),
    tree_config           JSONB,
    last_updated_at       TIMESTAMPTZ,
    created_at            TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_insight_type_name ON memory_insight_type(name);

CREATE TABLE IF NOT EXISTS memory_insight (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id            BIGINT                   NOT NULL,
    user_id           VARCHAR(64)              NOT NULL,
    agent_id          VARCHAR(64)              NOT NULL,
    memory_id         VARCHAR(200)             NOT NULL,
    type              VARCHAR(128)             NOT NULL,
    scope             VARCHAR(16)              NOT NULL,
    name              VARCHAR(256),
    categories        JSONB,
    content           TEXT,
    points            JSONB,
    group_name        VARCHAR(64),
    last_reasoned_at  TIMESTAMPTZ,
    summary_embedding JSONB,
    tier              VARCHAR(16),
    parent_insight_id BIGINT,
    child_insight_ids JSONB,
    version           INT                      NOT NULL DEFAULT 1,
    created_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_insight_biz_id ON memory_insight(user_id, agent_id, biz_id);
CREATE INDEX IF NOT EXISTS idx_insight_memory_id ON memory_insight(user_id, agent_id);
CREATE INDEX IF NOT EXISTS idx_insight_type ON memory_insight(user_id, agent_id, type);
CREATE INDEX IF NOT EXISTS idx_insight_parent ON memory_insight(user_id, agent_id, parent_insight_id);
CREATE INDEX IF NOT EXISTS idx_insight_tier ON memory_insight(user_id, agent_id, tier);
CREATE INDEX IF NOT EXISTS idx_insight_tier_group ON memory_insight(user_id, agent_id, type, tier, group_name);

CREATE TABLE IF NOT EXISTS memory_conversation_buffer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(128)             NOT NULL,
    user_id    VARCHAR(64)              NOT NULL,
    agent_id   VARCHAR(64)              NOT NULL,
    memory_id  VARCHAR(200)             NOT NULL,
    role       VARCHAR(16)              NOT NULL,
    content    TEXT                     NOT NULL,
    user_name  VARCHAR(64),
    source_client VARCHAR(64),
    timestamp  TIMESTAMPTZ,
    extracted  BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted    BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_buf_pending
    ON memory_conversation_buffer(session_id, extracted, deleted, id);
CREATE INDEX IF NOT EXISTS idx_buf_recent ON memory_conversation_buffer(session_id, deleted, id);
CREATE INDEX IF NOT EXISTS idx_buf_memory_id ON memory_conversation_buffer(user_id, agent_id, deleted, id);

CREATE TABLE IF NOT EXISTS memory_insight_buffer (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           VARCHAR(64)              NOT NULL,
    agent_id          VARCHAR(64)              NOT NULL,
    memory_id         VARCHAR(200)             NOT NULL,
    insight_type_name VARCHAR(128)             NOT NULL,
    item_id           BIGINT                   NOT NULL,
    group_name        VARCHAR(64),
    built             BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_insight_buffer
    ON memory_insight_buffer(user_id, agent_id, insight_type_name, item_id);
CREATE INDEX IF NOT EXISTS idx_insight_buf_type
    ON memory_insight_buffer(user_id, agent_id, insight_type_name);
CREATE INDEX IF NOT EXISTS idx_insight_buf_group
    ON memory_insight_buffer(user_id, agent_id, insight_type_name, group_name);

-- === V2__init_text_search.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS idx_item_content_trgm
    ON memory_item USING GIN (content gin_trgm_ops)
    WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_insight_content_trgm
    ON memory_insight USING GIN ((COALESCE(content, '')) gin_trgm_ops)
    WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_raw_data_segment_content_trgm
    ON memory_raw_data USING GIN ((COALESCE(segment ->> 'content', '')) gin_trgm_ops)
    WHERE deleted = FALSE;

-- === V3__multimodal.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_resource (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id     VARCHAR(64)  NOT NULL,
    user_id    VARCHAR(64)  NOT NULL,
    agent_id   VARCHAR(64)  NOT NULL,
    memory_id  VARCHAR(200) NOT NULL,
    source_uri VARCHAR(1024),
    storage_uri VARCHAR(1024),
    file_name  VARCHAR(512),
    mime_type  VARCHAR(128),
    checksum   VARCHAR(128),
    size_bytes BIGINT,
    metadata   JSONB,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_resource_biz_id
    ON memory_resource(user_id, agent_id, biz_id);
CREATE INDEX IF NOT EXISTS idx_resource_memory_id
    ON memory_resource(user_id, agent_id);

ALTER TABLE memory_raw_data
    ADD COLUMN IF NOT EXISTS resource_id VARCHAR(64),
    ADD COLUMN IF NOT EXISTS mime_type VARCHAR(128);
CREATE INDEX IF NOT EXISTS idx_raw_data_resource_id
    ON memory_raw_data(user_id, agent_id, resource_id);

-- === V4__bubble_state.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_insight_bubble_state (
    id           BIGSERIAL PRIMARY KEY,
    memory_id    VARCHAR(255) NOT NULL,
    tier         VARCHAR(32)  NOT NULL,
    insight_type VARCHAR(255) NOT NULL,
    dirty_count  INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    UNIQUE(memory_id, tier, insight_type)
);

-- === V5__item_temporal_fields.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- Temporal item columns are ensured by MemoryStoreDdl for dialect-safe upgrades.
SELECT 1;

-- === V6__graph_store.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_graph_entity (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR(64)  NOT NULL,
    agent_id     VARCHAR(64)  NOT NULL,
    memory_id    VARCHAR(200) NOT NULL,
    entity_key   VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    entity_type  VARCHAR(32)  NOT NULL,
    metadata     JSONB,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_graph_entity_identity
    ON memory_graph_entity(memory_id, entity_key);

CREATE TABLE IF NOT EXISTS memory_item_entity_mention (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(64)  NOT NULL,
    agent_id   VARCHAR(64)  NOT NULL,
    memory_id  VARCHAR(200) NOT NULL,
    item_id    BIGINT       NOT NULL,
    entity_key VARCHAR(255) NOT NULL,
    confidence REAL,
    metadata   JSONB,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_entity_mention_identity
    ON memory_item_entity_mention(memory_id, item_id, entity_key);
CREATE INDEX IF NOT EXISTS idx_item_entity_mention_item
    ON memory_item_entity_mention(memory_id, item_id);
CREATE INDEX IF NOT EXISTS idx_item_entity_mention_entity_key
    ON memory_item_entity_mention(memory_id, entity_key);

CREATE TABLE IF NOT EXISTS memory_item_link (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        VARCHAR(64)  NOT NULL,
    agent_id       VARCHAR(64)  NOT NULL,
    memory_id      VARCHAR(200) NOT NULL,
    source_item_id BIGINT       NOT NULL,
    target_item_id BIGINT       NOT NULL,
    link_type      VARCHAR(32)  NOT NULL,
    strength       DOUBLE PRECISION,
    metadata       JSONB,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_link_identity
    ON memory_item_link(memory_id, source_item_id, target_item_id, link_type);
CREATE INDEX IF NOT EXISTS idx_item_link_source_type
    ON memory_item_link(memory_id, source_item_id, link_type);
CREATE INDEX IF NOT EXISTS idx_item_link_target_type
    ON memory_item_link(memory_id, target_item_id, link_type);

CREATE TABLE IF NOT EXISTS memory_entity_cooccurrence (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            VARCHAR(64)  NOT NULL,
    agent_id           VARCHAR(64)  NOT NULL,
    memory_id          VARCHAR(200) NOT NULL,
    left_entity_key    VARCHAR(255) NOT NULL,
    right_entity_key   VARCHAR(255) NOT NULL,
    cooccurrence_count INTEGER      NOT NULL,
    metadata           JSONB,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_entity_cooccurrence_identity
    ON memory_entity_cooccurrence(memory_id, left_entity_key, right_entity_key);

-- === V8__graph_entity_alias_store.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_graph_entity_alias (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            VARCHAR(64)  NOT NULL,
    agent_id           VARCHAR(64)  NOT NULL,
    memory_id          VARCHAR(200) NOT NULL,
    entity_key         VARCHAR(255) NOT NULL,
    entity_type        VARCHAR(32)  NOT NULL,
    normalized_alias   VARCHAR(255) NOT NULL,
    evidence_count     INTEGER      NOT NULL,
    metadata           JSONB,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_graph_entity_alias_identity
    ON memory_graph_entity_alias(memory_id, entity_type, entity_key, normalized_alias);
CREATE INDEX IF NOT EXISTS idx_graph_entity_alias_lookup
    ON memory_graph_entity_alias(memory_id, entity_type, normalized_alias);

-- === V9__item_temporal_lookup.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- Temporal lookup columns, backfill, and indexes are ensured by MemoryStoreDdl.
SELECT 1;

-- === V10__item_graph_evolution.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

ALTER TABLE memory_item
    ADD COLUMN extraction_batch_id VARCHAR(64);
CREATE INDEX idx_memory_item_batch ON memory_item(memory_id, extraction_batch_id);

ALTER TABLE memory_item_link
    ADD COLUMN relation_code VARCHAR(64),
    ADD COLUMN evidence_source VARCHAR(64);

CREATE TABLE IF NOT EXISTS memory_item_graph_batch (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   VARCHAR(64)  NOT NULL,
    agent_id                  VARCHAR(64)  NOT NULL,
    memory_id                 VARCHAR(200) NOT NULL,
    extraction_batch_id       VARCHAR(64)  NOT NULL,
    state                     VARCHAR(32)  NOT NULL,
    error_message             VARCHAR(1024),
    retry_promotion_supported BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at                TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                   BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_graph_batch_identity
    ON memory_item_graph_batch(memory_id, extraction_batch_id);

CREATE TABLE IF NOT EXISTS memory_graph_alias_batch_receipt (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             VARCHAR(64)  NOT NULL,
    agent_id            VARCHAR(64)  NOT NULL,
    memory_id           VARCHAR(200) NOT NULL,
    entity_key          VARCHAR(255) NOT NULL,
    entity_type         VARCHAR(32)  NOT NULL,
    normalized_alias    VARCHAR(255) NOT NULL,
    extraction_batch_id VARCHAR(64)  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_graph_alias_batch_receipt_identity
    ON memory_graph_alias_batch_receipt(
        memory_id,
        entity_key,
        entity_type,
        normalized_alias,
        extraction_batch_id
    );

-- === V11__simplified_thread_core_v1.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_thread (
    id                        BIGSERIAL    PRIMARY KEY,
    memory_id                 VARCHAR(200) NOT NULL,
    thread_key                VARCHAR(255) NOT NULL,
    thread_type               VARCHAR(32)  NOT NULL,
    anchor_kind               VARCHAR(64)  NOT NULL,
    anchor_key                VARCHAR(255) NOT NULL,
    display_label             VARCHAR(255),
    lifecycle_status          VARCHAR(32)  NOT NULL,
    object_state              VARCHAR(32)  NOT NULL,
    headline                  TEXT,
    snapshot_json             JSONB        NOT NULL,
    snapshot_version          INTEGER      NOT NULL,
    opened_at                 TIMESTAMPTZ,
    last_event_at             TIMESTAMPTZ,
    last_meaningful_update_at TIMESTAMPTZ,
    closed_at                 TIMESTAMPTZ,
    event_count               BIGINT       NOT NULL,
    member_count              BIGINT       NOT NULL,
    created_at                TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_memory_thread_key
    ON memory_thread(memory_id, thread_key);
CREATE UNIQUE INDEX IF NOT EXISTS uk_memory_thread_anchor
    ON memory_thread(memory_id, anchor_kind, anchor_key);

CREATE TABLE IF NOT EXISTS memory_thread_event (
    id                    BIGSERIAL    PRIMARY KEY,
    memory_id             VARCHAR(200) NOT NULL,
    thread_key            VARCHAR(255) NOT NULL,
    event_key             VARCHAR(255) NOT NULL,
    event_seq             BIGINT       NOT NULL,
    event_type            VARCHAR(32)  NOT NULL,
    event_time            TIMESTAMPTZ  NOT NULL,
    event_payload_json    JSONB        NOT NULL,
    event_payload_version INTEGER      NOT NULL,
    is_meaningful         BOOLEAN      NOT NULL,
    confidence            DOUBLE PRECISION,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_memory_thread_event
    ON memory_thread_event(memory_id, thread_key, event_key);
CREATE INDEX IF NOT EXISTS idx_memory_thread_event_seq
    ON memory_thread_event(memory_id, thread_key, event_seq);

CREATE TABLE IF NOT EXISTS memory_thread_membership (
    id                BIGSERIAL    PRIMARY KEY,
    memory_id         VARCHAR(200) NOT NULL,
    thread_key        VARCHAR(255) NOT NULL,
    item_id           BIGINT       NOT NULL,
    role              VARCHAR(32)  NOT NULL,
    is_primary        BOOLEAN      NOT NULL,
    relevance_weight  DOUBLE PRECISION NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_memory_thread_membership
    ON memory_thread_membership(memory_id, thread_key, item_id);
CREATE INDEX IF NOT EXISTS idx_memory_thread_membership_item
    ON memory_thread_membership(memory_id, item_id);

CREATE TABLE IF NOT EXISTS thread_intake_outbox (
    id                      BIGSERIAL    PRIMARY KEY,
    memory_id               VARCHAR(200) NOT NULL,
    trigger_item_id         BIGINT       NOT NULL,
    enqueue_generation      BIGINT       NOT NULL DEFAULT 1,
    status                  VARCHAR(32)  NOT NULL,
    attempt_count           INTEGER      NOT NULL,
    claimed_at              TIMESTAMPTZ,
    lease_expires_at        TIMESTAMPTZ,
    failure_reason          VARCHAR(255),
    last_processed_item_id  BIGINT,
    enqueued_at             TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_thread_intake_outbox
    ON thread_intake_outbox(memory_id, trigger_item_id);
CREATE INDEX IF NOT EXISTS idx_thread_intake_outbox_status
    ON thread_intake_outbox(memory_id, status, trigger_item_id);

CREATE TABLE IF NOT EXISTS memory_thread_runtime (
    memory_id                      VARCHAR(200) NOT NULL PRIMARY KEY,
    projection_state               VARCHAR(32)  NOT NULL,
    pending_count                  BIGINT       NOT NULL,
    failed_count                   BIGINT       NOT NULL,
    last_enqueued_item_id          BIGINT,
    last_processed_item_id         BIGINT,
    rebuild_in_progress            BOOLEAN      NOT NULL,
    rebuild_cutoff_item_id         BIGINT,
    materialization_policy_version VARCHAR(64)  NOT NULL,
    invalidation_reason            VARCHAR(255),
    updated_at                     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO memory_thread_runtime (
    memory_id,
    projection_state,
    pending_count,
    failed_count,
    last_enqueued_item_id,
    last_processed_item_id,
    rebuild_in_progress,
    rebuild_cutoff_item_id,
    materialization_policy_version,
    invalidation_reason,
    updated_at
)
SELECT src.memory_id,
       'REBUILD_REQUIRED',
       0,
       0,
       NULL,
       NULL,
       FALSE,
       NULL,
       'thread-core-v1',
       'migration bootstrap',
       CURRENT_TIMESTAMP
FROM (
    SELECT DISTINCT memory_id
    FROM memory_item
    WHERE deleted = FALSE
) src
WHERE src.memory_id IS NOT NULL
  AND NOT EXISTS (
        SELECT 1
        FROM memory_thread_runtime runtime
        WHERE runtime.memory_id = src.memory_id
    );

-- === V12__memory_thread_enrichment_input.sql ===
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_thread_enrichment_input (
    id                                   BIGSERIAL    PRIMARY KEY,
    memory_id                            VARCHAR(200) NOT NULL,
    thread_key                           VARCHAR(255) NOT NULL,
    input_run_key                        VARCHAR(255) NOT NULL,
    entry_seq                            INTEGER      NOT NULL,
    basis_cutoff_item_id                 BIGINT       NOT NULL,
    basis_meaningful_event_count         BIGINT       NOT NULL,
    basis_materialization_policy_version VARCHAR(64)  NOT NULL,
    payload_json                         JSONB        NOT NULL,
    provenance_json                      JSONB        NOT NULL,
    created_at                           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_memory_thread_enrichment_input_run_entry
    ON memory_thread_enrichment_input(memory_id, input_run_key, entry_seq);

CREATE INDEX IF NOT EXISTS idx_memory_thread_enrichment_input_replay
    ON memory_thread_enrichment_input(
        memory_id,
        basis_materialization_policy_version,
        basis_cutoff_item_id,
        basis_meaningful_event_count,
        input_run_key,
        entry_seq
    );

